// Copies the browser engines into public/ so they are served as plain static files:
//  - Ghostscript WebAssembly (compression)
//  - pdf.js resources, in a folder named after the pdf.js version so browsers never reuse a stale copy:
//      pdf.worker.js    page-rendering worker for the fallback renderer (renamed to .js so every
//                       web server sends the correct JavaScript type)
//      standard_fonts/  the 14 standard PDF fonts (Helvetica, Times...) when a PDF does not embed them
//      cmaps/           character maps for Chinese, Japanese and Korean text
//      wasm/            decoders for JPEG 2000 and JBIG2 images, common in scanner output
//      iccs/            colour profiles
import { copyFileSync, cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';

const gs = 'node_modules/@jspawn/ghostscript-wasm/';
mkdirSync('public/gs', { recursive: true });
for (const f of ['gs.js', 'gs.wasm']) copyFileSync(gs + f, 'public/gs/' + f);

const pdfjsDir = 'node_modules/pdfjs-dist/';
const { version } = JSON.parse(readFileSync(pdfjsDir + 'package.json', 'utf8'));
const out = `public/pdfjs/${version}/`;
rmSync('public/pdfjs', { recursive: true, force: true });
mkdirSync(out + 'wasm', { recursive: true });
copyFileSync(pdfjsDir + 'legacy/build/pdf.worker.min.mjs', out + 'pdf.worker.js');
for (const d of ['standard_fonts', 'cmaps', 'iccs']) cpSync(pdfjsDir + d, out + d, { recursive: true });
for (const f of [
  'openjpeg.wasm',
  'openjpeg_nowasm_fallback.js',
  'jbig2.wasm',
  'jbig2_nowasm_fallback.js',
  'qcms_bg.wasm',
  'LICENSE_OPENJPEG',
  'LICENSE_JBIG2',
  'LICENSE_QCMS',
]) {
  copyFileSync(pdfjsDir + 'wasm/' + f, out + 'wasm/' + f);
}

writeFileSync(
  'src/lib/pdfjs-worker.ts',
  `// Generated by scripts/copy-gs.mjs\nexport const PDFJS_BASE = 'pdfjs/${version}/';\nexport const PDFJS_WORKER = PDFJS_BASE + 'pdf.worker.js';\n`,
);

console.log(`Engines copied: Ghostscript -> public/gs, pdf.js resources -> ${out}`);
