// Copies the browser engines into public/ so they are served as plain static files:
//  - Ghostscript WebAssembly (compression)
//  - pdf.js worker (page rendering), renamed to .js so every web server sends the
//    correct JavaScript type, with the version in the name so browsers never reuse a stale copy.
import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';

const gs = 'node_modules/@jspawn/ghostscript-wasm/';
mkdirSync('public/gs', { recursive: true });
for (const f of ['gs.js', 'gs.wasm']) copyFileSync(gs + f, 'public/gs/' + f);

const { version } = JSON.parse(readFileSync('node_modules/pdfjs-dist/package.json', 'utf8'));
mkdirSync('public/pdfjs', { recursive: true });
for (const f of readdirSync('public/pdfjs')) rmSync('public/pdfjs/' + f);
const workerName = `pdf.worker-${version}.js`;
copyFileSync('node_modules/pdfjs-dist/legacy/build/pdf.worker.min.mjs', 'public/pdfjs/' + workerName);
writeFileSync('src/lib/pdfjs-worker.ts', `// Generated by scripts/copy-gs.mjs\nexport const PDFJS_WORKER = 'pdfjs/${workerName}';\n`);

console.log(`Engines copied: Ghostscript -> public/gs, pdf.js worker -> public/pdfjs/${workerName}`);
